# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    ## Checkout the code from Repo
    - name: Checkout Code from Repo
      uses: actions/checkout@v3
    ## Setup python environment
    - name: Setup python environment
      uses: actions/setup@v3
      with:
        python-version: "3.12.2"
    ## Install all dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    ## Run tests    
    - name: Run tests
      run: |
        pytest
