name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code from Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4  # Fixed action name from setup to setup-python
      with:
        python-version: "3.12.2"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov  # Added test coverage reporting
        if [ -f requirements.txt ]; then  # Added check if requirements.txt exists
            pip install -r requirements.txt
        fi

    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()  # Run even if tests fail
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
